"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { CitationMediaPlayer } from "@/app/components/canonical-repository/CitationMediaPlayer";

type Ref = { osis: string; display: string };
type Topic = { topic_ids: string[]; path: string[]; role: "primary" | "secondary" };
type Unit = { unit_id:string; title:string; unit_type:"passage"|"concept"; status:string; primary_bible_refs:Ref[]; topic_assignments:Topic[]; manuscript:any; citation_ids:string[]; relationship_ids:string[]; aliases:string[]; review:any; schema_version:number };
type Summary = { unit_id:string; title:string; unit_type:string; status:string; primary_bible_refs:Ref[] };

export default function UnitReviewPage() {
  const params = useParams();
  const unitId = decodeURIComponent(Array.isArray(params.unitId) ? params.unitId[0] : String(params.unitId));
  const [unit,setUnit]=useState<Unit|null>(null); const [citations,setCitations]=useState<any[]>([]); const [allUnits,setAllUnits]=useState<Summary[]>([]);
  const [manuscriptMarkdown,setManuscriptMarkdown]=useState("");
  const [message,setMessage]=useState(""); const [mergeFilter,setMergeFilter]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [mergePreview,setMergePreview]=useState<any>(null);
  const [sourceProject,setSourceProject]=useState(""); const [sourceStart,setSourceStart]=useState("1"); const [sourceEnd,setSourceEnd]=useState("1"); const [sourceExcerpt,setSourceExcerpt]=useState("");
  const load=async()=>{const [detail,list]=await Promise.all([fetch(`/api/admin/canonical-repository/units/${encodeURIComponent(unitId)}`,{cache:'no-store'}).then(r=>r.json()),fetch('/api/admin/canonical-repository/units',{cache:'no-store'}).then(r=>r.json())]);setUnit(detail.unit);setCitations(detail.citations??[]);setManuscriptMarkdown(detail.manuscript_markdown??"");setAllUnits(list.units??[]);};
  useEffect(()=>{void load();},[unitId]);
  const related=useMemo(()=>allUnits.filter(item=>item.unit_id!==unitId&&item.status!=="archived"&&(!mergeFilter||`${item.title} ${item.primary_bible_refs.map(r=>r.display).join(' ')}`.toLowerCase().includes(mergeFilter.toLowerCase()))).slice(0,20),[allUnits,mergeFilter,unitId]);
  if(!unit)return <main className="p-10 text-center">讀取中…</main>;
  const save=async(nextUnit:Unit=unit)=>{setMessage(nextUnit.status==='published'?'正在發布並更新公開文庫…':'儲存中…');const response=await fetch(`/api/admin/canonical-repository/units/${encodeURIComponent(unitId)}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(nextUnit)});const data=await response.json();const failure=typeof data.detail==='string'?data.detail:data.detail?.findings?.join('；')??'無法儲存';setMessage(response.ok?(nextUnit.status==='published'?'已發布，公開文庫已更新。':'已儲存；若此單元原已發布，公開文庫也已同步。'):failure);if(response.ok)setUnit(data);};
  const approveCitation=async(item:any)=>{const updated={...item.citation,status:'approved',reviewed_at:new Date().toISOString(),reviewed_by:'editor'};const response=await fetch(`/api/admin/canonical-repository/citations/${encodeURIComponent(updated.citation_id)}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(updated)});setMessage(response.ok?'來源引用已批准。':'來源引用批准失敗');if(response.ok)await load();};
  const merge=async(apply:boolean)=>{const response=await fetch(`/api/admin/canonical-repository/units/${encodeURIComponent(unitId)}/merge`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({absorbed_unit_ids:selected,apply})});const data=await response.json();if(response.ok){setMergePreview(data);setMessage(apply?'合併完成；被吸收單元已封存，目標單元回到待審閱。':'合併預覽已產生，尚未改動資料。');if(apply)await load();}else setMessage(data.detail??'合併失敗');};
  const addSource=async()=>{setMessage('正在建立來源定位…');const rebuild=await fetch('/api/admin/canonical-repository/source-maps/rebuild',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({project_ids:[sourceProject]})});const rebuilt=await rebuild.json();const item=rebuilt.results?.[0];if(!rebuild.ok||item?.status!=='completed'){setMessage(item?.error??'無法建立 source map');return;}const response=await fetch(`/api/admin/canonical-repository/units/${encodeURIComponent(unitId)}/citations`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({source_id:item.source.source_id,start_line:Number(sourceStart),end_line:Number(sourceEnd),highlight_text:sourceExcerpt.trim()||null,evidence_ids:[],supports_claim:unit.title})});const data=await response.json();setMessage(response.ok?'來源引用已建立，請檢查高亮後再批准。':data.detail??'建立引用失敗');if(response.ok){setSourceExcerpt('');await load();}};
  const canPublish=citations.length>0&&citations.every(item=>item.citation.status==='approved'&&item.resolution.state==='valid');
  return <main className="mx-auto max-w-5xl px-6 py-10"><Link href="/admin/canonical-repository" className="text-sm font-semibold text-indigo-600">← 返回單元列表</Link>
    <div className="mt-5 flex flex-wrap justify-between gap-4"><div><p className="text-sm text-slate-500">{unit.unit_id}</p><h1 className="text-3xl font-bold">單元審閱</h1></div><div className="flex flex-wrap gap-3">{unit.status==='published'?<Link href={`/resources/wang-repository/${encodeURIComponent(unit.unit_id)}`} className="rounded-lg border border-indigo-300 px-5 py-2 font-semibold text-indigo-700">查看公開單元</Link>:<button disabled={!canPublish} onClick={()=>save({...unit,status:'published'})} title={canPublish?'发布并同步公开文库':'所有来源获批准后才可发布'} className="rounded-lg bg-indigo-600 px-5 py-2 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">發布至公開文庫</button>}<button onClick={()=>save()} className="rounded-lg bg-emerald-600 px-5 py-2 font-semibold text-white">儲存變更</button></div></div>
    {message?<p className="mt-4 rounded-lg bg-blue-50 px-4 py-3 text-blue-800">{message}</p>:null}
    <section className="mt-6 space-y-5 rounded-xl border bg-white p-6 shadow-sm"><label className="block"><span className="text-sm font-semibold">單元標題</span><input value={unit.title} onChange={e=>setUnit({...unit,title:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2"/></label>
      <div className="grid gap-4 md:grid-cols-2"><label><span className="text-sm font-semibold">類型</span><select value={unit.unit_type} onChange={e=>setUnit({...unit,unit_type:e.target.value as Unit['unit_type']})} className="mt-1 w-full rounded-lg border px-3 py-2"><option value="passage">釋經／經文單元</option><option value="concept">跨經文主題單元</option></select></label><label><span className="text-sm font-semibold">審閱狀態</span><select value={unit.status} onChange={e=>setUnit({...unit,status:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2"><option value="candidate">待審閱</option><option value="reviewed">已審閱</option>{unit.status==='published'?<option value="published">已發布</option>:null}<option value="archived">封存</option></select><span className="mt-1 block text-xs text-slate-500">发布请使用页面上方的“发布至公开文库”按钮。</span></label></div>
      <label className="block"><span className="text-sm font-semibold">經文（每行：OSIS | 顯示文字）</span><textarea rows={4} value={unit.primary_bible_refs.map(r=>`${r.osis} | ${r.display}`).join('\n')} onChange={e=>setUnit({...unit,primary_bible_refs:e.target.value.split('\n').filter(Boolean).map(line=>{const [osis,display]=line.split('|').map(v=>v.trim());return {osis,display:display||osis};})})} className="mt-1 w-full rounded-lg border px-3 py-2 font-mono text-sm"/></label>
      <label className="block"><span className="text-sm font-semibold">主題路徑（每行用 › 分層）</span><textarea rows={4} value={unit.topic_assignments.map(t=>t.path.join(' › ')).join('\n')} onChange={e=>setUnit({...unit,topic_assignments:e.target.value.split('\n').filter(Boolean).map((line,index)=>({path:line.split('›').map(v=>v.trim()),topic_ids:unit.topic_assignments[index]?.topic_ids??[],role:index===0?'primary':'secondary'}))})} className="mt-1 w-full rounded-lg border px-3 py-2"/></label>
      <div className="border-t pt-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">Manuscript 內容</h2><Link className="text-sm font-semibold text-indigo-600 hover:underline" href={`/admin/notes-to-sermon/project/${encodeURIComponent(unit.manuscript.project_id)}`}>開啟完整 Manuscript：{unit.manuscript.heading_title}</Link></div>{manuscriptMarkdown.trim()?<article className="prose prose-slate mt-4 max-w-none rounded-lg bg-slate-50 px-5 py-4"><ReactMarkdown remarkPlugins={[remarkGfm]}>{manuscriptMarkdown}</ReactMarkdown></article>:<p className="mt-3 text-sm text-amber-700">尚未找到這個單元的 Manuscript 內容。</p>}</div></section>
      <section className="mt-6 rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">原始來源</h2>{citations.length===0?<p className="mt-3 text-amber-700">尚無來源引用；此單元不可發布。</p>:<div className="mt-3 space-y-3">{citations.map(item=><div key={item.citation.citation_id} className="rounded-lg border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><a href={item.resolution.deep_link_url} target="_blank" rel="noopener noreferrer" className="font-semibold text-indigo-700 hover:underline">{item.resolution.source.title}</a><div className="flex items-center gap-2"><span className={`rounded px-2 py-1 text-xs font-semibold ${item.citation.status==='approved'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{item.citation.status==='approved'?'已批准':'待批准'}</span>{item.citation.status!=='approved'&&item.resolution.state==='valid'?<button onClick={()=>approveCitation(item)} className="rounded border border-emerald-300 px-3 py-1 text-xs font-semibold text-emerald-700">批准來源</button>:null}</div></div><CitationMediaPlayer source={item.resolution.source} startTime={item.resolution.locator?.start_time}/><div className="prose prose-slate mt-4 max-w-none text-sm"><ReactMarkdown remarkPlugins={[remarkGfm]}>{item.resolution.highlight_text}</ReactMarkdown></div></div>)}</div>}<div className="mt-6 border-t pt-5"><h3 className="font-bold">新增精確來源</h3><p className="mt-1 text-sm text-slate-600">輸入來源 Project ID 和 Unified Input 行號；摘錄若留空，會保留整個原始段落或頁面範圍。</p><div className="mt-3 grid gap-3 md:grid-cols-3"><input value={sourceProject} onChange={e=>setSourceProject(e.target.value)} placeholder="來源 Project ID" className="rounded border px-3 py-2 md:col-span-3"/><input value={sourceStart} onChange={e=>setSourceStart(e.target.value)} type="number" min="1" placeholder="開始行" className="rounded border px-3 py-2"/><input value={sourceEnd} onChange={e=>setSourceEnd(e.target.value)} type="number" min="1" placeholder="結束行" className="rounded border px-3 py-2"/><button disabled={!sourceProject.trim()} onClick={addSource} className="rounded bg-indigo-600 px-4 py-2 font-semibold text-white disabled:opacity-40">建立 Citation</button><textarea value={sourceExcerpt} onChange={e=>setSourceExcerpt(e.target.value)} placeholder="精確原文摘錄（可選）" rows={3} className="rounded border px-3 py-2 md:col-span-3"/></div></div></section>
    <section className="mt-6 rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">合併重複／跨經文單元</h2><p className="mt-1 text-sm text-slate-600">先預覽；確認後才封存被吸收單元。所有 citation、經文和主題都會保留。</p><input value={mergeFilter} onChange={e=>setMergeFilter(e.target.value)} placeholder="搜尋要合併的單元…" className="mt-4 w-full rounded-lg border px-3 py-2"/><div className="mt-3 max-h-64 space-y-2 overflow-auto">{related.map(item=><label key={item.unit_id} className="flex gap-3 rounded border p-3"><input type="checkbox" checked={selected.includes(item.unit_id)} onChange={e=>setSelected(e.target.checked?[...selected,item.unit_id]:selected.filter(id=>id!==item.unit_id))}/><span><strong>{item.title}</strong><small className="ml-2 text-slate-500">{item.primary_bible_refs.map(r=>r.display).join('、')}</small></span></label>)}</div><div className="mt-4 flex gap-3"><button disabled={!selected.length} onClick={()=>merge(false)} className="rounded-lg border px-4 py-2 font-semibold disabled:opacity-40">預覽合併</button><button disabled={!mergePreview||!selected.length} onClick={()=>merge(true)} className="rounded-lg bg-rose-600 px-4 py-2 font-semibold text-white disabled:opacity-40">確認合併</button></div>{mergePreview?<pre className="mt-4 overflow-auto rounded bg-slate-950 p-4 text-xs text-white">{JSON.stringify(mergePreview.changes,null,2)}</pre>:null}</section>
  </main>;
}
