import { Mails } from "lucide-react";
import { FC } from "react";

export const Footer: FC = () => {
  return (
    <div className="text-center flex flex-col items-center text-xs text-zinc-700 gap-1">
      <div className="text-zinc-400">
        Answer generated by large language models, plz double check for correctness.
      </div>
      <div className="flex gap-2 justify-center">
        <div>
          <a
            className="text-blue-500 font-medium inline-flex gap-1 items-center flex-nowrap text-nowrap"
            href="mailto:junyang@smart-answer.ai"
          >
            <Mails size={8} />
            Contact us
          </a>
        </div>
      </div>

      <div className="flex items-center justify-center flex-wrap gap-x-4 gap-y-2 mt-2 text-zinc-400">
        <a className="hover:text-zinc-950" href="https://smart-answer.ai/">
          Smart Answer Home
        </a>
        <a
          className="hover:text-zinc-950"
          href="https://github.com/junyang168/smart-answer"
        >
          Source Code
        </a>
        <a className="hover:text-zinc-950" href="https://medium.com/@junyang168/smart-answer-turning-enterprise-applications-into-ai-powered-chatbot-4b1aabce6c9d">
          Technical Overview
        </a>
      </div>
    </div>
  );
};
