from pydantic import BaseModel, Field
from typing import List, Optional, Dict
from enum import Enum

class AgentRole(str, Enum):
    CHIEF_EDITOR = "chief_editor"
    EXEGETE = "exegete"
    THEOLOGIAN = "theologian"
    ILLUSTRATOR = "illustrator"
    HOMILETICIAN = "homiletician" # Drafter
    CRITIC = "critic"
    STRUCTURING_SPECIALIST = "structuring_specialist"

class Illustration(BaseModel):
    theme: str
    description: str
    type: str # Modern, Historical, Nature

class ExegeticalNote(BaseModel):
    verse: str
    original_text: str
    meaning: str
    historical_context: str

class AgentState(BaseModel):
    # --- Context (Inputs) ---
    project_id: str
    sermon_series_title: str
    sermon_series_description: str
    lecture_title: str
    lecture_description: str
    
    # The core material
    source_notes: str # The unified markdown from OCR
    
    # --- Phase 1: Research Artifacts ---
    exegetical_notes: Optional[str] = None # Markdown generated by Exegete
    
    # --- Phase 2: Enrichment Artifacts ---
    theological_analysis: Optional[str] = None # Markdown from Theologian
    illustration_ideas: Optional[str] = None # Markdown from Illustrator
    
    # --- Phase 3: Drafting ---
    beats: Optional[List[str]] = None # Saved structure
    # We might draft in chunks
    draft_chunks: List[str] = Field(default_factory=list)
    full_manuscript: Optional[str] = None
    
    # --- Logging/Feedback ---
    processing_logs: List[str] = Field(default_factory=list)
    
    def add_log(self, message: str):
        self.processing_logs.append(message)
