"""Where a sermon with no headings gets its section boundaries.

One call, two readers. The sermon editor shows the suggestions to a person who
decides whether to insert them; the extraction pipeline takes every `level == 1`
suggestion as a **section boundary**, and a transcript is extracted one section
at a time. 90 of 115 published transcripts carry no headings at all, so for most
of the corpus this call decides how the source is cut.

It used to be a hardcoded prompt inside `GeminiClient.generate_subtitles`, an
unschema'd `generate_content`, a hand-stripped ```json fence, and this:

    except Exception as e:
        print(f"Error generating subtitles: {e}")
        return []

An empty list reaches `sections_from_generator` as "no boundaries", which is one
section, which is whole-document extraction -- the exact behaviour #88 replaced
after measuring it at 50% sentence coverage. Nothing anywhere said the cut had
been generated and the generation had failed; the package simply looked like a
source that happened to have one section. The editor showed the same empty list
as 「AI 未能產生任何小標題建議。」, so a crashed call and an honest "nothing to
suggest" were the same sentence to the user.

So: failure raises. Both readers are better served by an error than by a
plausible-looking answer nobody can tell apart from a real one.

Everything else follows from moving onto `Stage1OpenAIClient`, which is where
the rest of this pipeline's model calls already live: a JSON schema instead of a
fence-stripping heuristic, a validation retry loop, `last_usage` to price, and a
prompt in `prompts/` that has a SHA and can enter a fingerprint.
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path
from typing import TYPE_CHECKING, Any, Mapping, Sequence

from backend.pipeline.llm_usage import usage_row
from backend.pipeline.run_ledger import run_record

if TYPE_CHECKING:  # pragma: no cover - import cost, not behaviour
    from backend.pipeline.stage1 import Stage1OpenAIClient

PROMPT_PATH = Path(__file__).with_name("prompts") / "sermon_subtitle_generation.md"

SCHEMA_VERSION = "wang_sermon_subtitles_v1"

#: The ledger stage these runs are filed under. Sectioning is its own unit of
#: work, not part of extraction: it happens before the extraction run's identity
#: can be computed (the plan is an input to the fingerprint), it is cached per
#: source hash so it runs at most once where extraction may run many times, and
#: the editor calls it without any extraction in sight.
LEDGER_STAGE = "sectioning"

#: `after_index` for a heading that belongs before the first paragraph. Spelled
#: exactly this way on the wire -- the editor matches the literal string.
START = "START"

VALIDATION_ATTEMPTS = 3

#: Subtitles used to be generated by whatever `FULL_ARTICLE_MODEL` happened to
#: name, which is a variable about a different feature: changing the full-article
#: model silently resegmented every headingless sermon. They get their own knob.
DEFAULT_SUBTITLE_MODEL = "gpt-5.6-sol"


class SubtitleGenerationError(RuntimeError):
    """The subtitles could not be generated. Never returns an empty list instead."""


class SubtitleValidationError(SubtitleGenerationError, ValueError):
    """The model answered, but the answer cannot be used. Goes back for a retry."""


SUBTITLE_SCHEMA: dict[str, Any] = {
    "name": SCHEMA_VERSION,
    "strict": True,
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "required": ["insertions"],
        "properties": {
            "insertions": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["after_index", "text", "level"],
                    "properties": {
                        # A paragraph index copied from the input, or "START".
                        # Free text on purpose: the editor's indices are opaque
                        # strings, not necessarily numbers.
                        "after_index": {"type": "string"},
                        "text": {"type": "string"},
                        "level": {"type": "integer"},
                    },
                },
            }
        },
    },
}


def subtitle_model() -> str:
    return os.getenv("SUBTITLE_MODEL") or DEFAULT_SUBTITLE_MODEL


def subtitle_reasoning_effort() -> str:
    return os.getenv("SUBTITLE_REASONING_EFFORT") or "medium"


def build_client(**overrides: Any) -> "Stage1OpenAIClient":
    """The client this call is made with.

    Imported here rather than at module scope: `backend.pipeline.stage1` reaches
    `backend.api`, whose package import builds the web app, and the sermon editor
    imports this module from inside that app.
    """

    from backend.pipeline.stage1 import Stage1OpenAIClient

    settings: dict[str, Any] = {
        "model": subtitle_model(),
        "reasoning_effort": subtitle_reasoning_effort(),
        "timeout_seconds": 600.0,
        "max_retries": 3,
        # A few dozen short headings, but `gpt-5.6-sol` spends its reasoning out
        # of the same budget, so this is sized for the thinking rather than the
        # answer.
        "max_output_tokens": 16000,
    }
    settings.update(overrides)
    return Stage1OpenAIClient(**settings)


def normalized_paragraphs(paragraphs: Sequence[Mapping[str, Any]]) -> list[dict[str, str]]:
    """`[{"index": ..., "text": ...}]` with both fields as strings.

    The editor sends its own paragraph records with a dozen other fields on
    them; the model needs two, and the smaller input is also the cheaper one.
    """

    return [
        {
            "index": str(paragraph.get("index")),
            # One paragraph per line, so a paragraph containing a newline cannot
            # look like two entries in the listing below.
            "text": " ".join(str(paragraph.get("text") or "").split()),
        }
        for paragraph in paragraphs
    ]


def render_paragraphs(paragraphs: Sequence[Mapping[str, str]]) -> str:
    """The listing the model reads: one line per paragraph, id first."""

    lines = "\n".join(f"[{row['index']}] {row['text']}" for row in paragraphs)
    return (
        f"以下是这篇讲道的全部段落，共 {len(paragraphs)} 段。"
        "方括号里的是段落 index，`after_index` 必须逐字复制其中之一，或写 START。\n\n"
        f"{lines}\n"
    )


def validate_insertions(
    candidate: Mapping[str, Any], paragraphs: Sequence[Mapping[str, str]]
) -> list[dict[str, Any]]:
    """Accept the answer only if every insertion lands somewhere real.

    `_position_after` used to drop an unrecognised `after_index` with a bare
    `continue`, so a hallucinated index cost a section boundary and said
    nothing. An index that does not name an input paragraph is a failed answer,
    and a failed answer is worth another attempt.
    """

    rows = candidate.get("insertions")
    if not isinstance(rows, list):
        raise SubtitleValidationError("回应里没有 insertions 数组")

    known = {row["index"] for row in paragraphs}
    problems: list[str] = []
    accepted: list[dict[str, Any]] = []
    for position, row in enumerate(rows, start=1):
        if not isinstance(row, Mapping):
            problems.append(f"第 {position} 条不是对象")
            continue
        after = str(row.get("after_index") or "").strip()
        text = str(row.get("text") or "").strip()
        level = row.get("level")
        if after.upper() == START:
            after = START
        elif after not in known:
            problems.append(
                f"第 {position} 条的 after_index「{after}」不是输入里的任何一个段落 index"
            )
        if level not in (1, 2):
            problems.append(f"第 {position} 条的 level 是 {level!r}，只能是 1 或 2")
        if not text:
            problems.append(f"第 {position} 条没有标题文字")
        accepted.append({"after_index": after, "text": text, "level": level})
    if problems:
        raise SubtitleValidationError("；".join(problems))
    return accepted


def _feedback(error: SubtitleValidationError) -> str:
    return (
        "\n\n===== 上一版未通过机械校验 =====\n"
        f"{error}\n"
        "`after_index` 只能逐字复制输入清单里出现过的段落 index，或写 START。"
        "请修正后重新输出完整 JSON。"
    )


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def generate_subtitles(
    paragraphs: Sequence[Mapping[str, Any]],
    *,
    subject: str,
    consumer: str,
    trigger: str = "cli",
    subject_kind: str = "source",
    client: "Stage1OpenAIClient | None" = None,
    attempts: int = VALIDATION_ATTEMPTS,
) -> list[dict[str, Any]]:
    """Suggest where this sermon breaks, or raise saying why it could not.

    Returns `[{"after_index": ..., "text": "## …", "level": 1}, …]`, which is
    the shape both readers already speak. An empty list means the model found no
    break worth marking -- an answer, not a failure; a failure is an exception.
    """

    rows = normalized_paragraphs(paragraphs)
    if not rows:
        raise SubtitleGenerationError(f"{subject}: no paragraphs to generate subtitles for")
    prompt = PROMPT_PATH.read_text(encoding="utf-8")
    listing = render_paragraphs(rows)
    client = client or build_client()

    with run_record(
        subject=subject, stage=LEDGER_STAGE, trigger=trigger, subject_kind=subject_kind
    ) as record:
        record.model(client.model)
        record.inputs({
            "prompt_sha256": _sha256(prompt),
            "paragraphs_sha256": _sha256(listing),
        })
        record.metadata({"consumer": consumer, "paragraph_count": len(rows)})
        last_error: SubtitleValidationError | None = None
        for attempt in range(1, attempts + 1):
            candidate = client.generate_json(
                prompt,
                _feedback(last_error) if last_error else "",
                SUBTITLE_SCHEMA,
                cache_prefix=listing,
            )
            # Recorded per attempt, before the answer is judged: a rejected
            # attempt was paid for, and a run whose usage is only handed over on
            # success prices its failures at nothing.
            record.usage([usage_row(client.last_usage, attempt)])
            try:
                insertions = validate_insertions(candidate, rows)
            except SubtitleValidationError as exc:
                last_error = exc
                continue
            record.quality({
                "insertions": len(insertions),
                "sections": 1 + sum(
                    1 for row in insertions
                    if row["level"] == 1 and row["after_index"] != START
                ),
            })
            record.metadata({"attempts": attempt})
            return insertions
        raise last_error or SubtitleGenerationError(
            f"{subject}: subtitle generation failed after {attempts} attempts"
        )
