import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Head from 'next/head';
import { Header } from "@/app/components/header";

const inter = Inter({ subsets: ["latin"] });

import SessionProvider from "./SessionProvider"; //next SessionProvider imported
import { getServerSession } from "next-auth";



export const metadata: Metadata = {
  title: "聖經講道問答",
  description:
    "Answer generated by large language models (LLMs). Double check for correctness.",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header show_signin="true"></Header>
        <SessionProvider>
            {children}
        </SessionProvider>
      </body>
    </html>
  );
}
